from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(record, output_path):

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    content = []

    # HEADER

    title = Paragraph(
        "NeuroLis AI - Brain MRI Analysis Report",
        styles["Title"]
    )

    content.append(title)
    content.append(Spacer(1, 20))

    subtitle = Paragraph(
        "AI-Assisted Neurological Health Platform",
        styles["Italic"]
    )

    content.append(subtitle)
    content.append(Spacer(1, 25))

    # REPORT DETAILS

    report_data = [

        ["Report ID", f"NLS-{record.id}"],
        ["Analysis Date", str(record.upload_date.strftime('%d %b %Y'))],
        ["Prediction", record.prediction],
        ["Confidence", f"{round(record.confidence,2)}%"]

    ]

    report_table = Table(
        report_data,
        colWidths=[150, 300]
    )

    report_table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

        ])
    )

    content.append(report_table)

    content.append(Spacer(1, 25))

    # RISK LEVEL

    if record.confidence >= 90:
        risk_level = "High Attention"

    elif record.confidence >= 75:
        risk_level = "Moderate Attention"

    else:
        risk_level = "Needs Further Evaluation"

    content.append(
        Paragraph(
            "<b>Risk Assessment</b>",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            risk_level,
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    # AI INTERPRETATION

    content.append(
        Paragraph(
            "AI Clinical Interpretation",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            record.explanation,
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # RECOMMENDED SPECIALISTS

    content.append(
        Paragraph(
            "Recommended Specialists",
            styles["Heading2"]
        )
    )

    specialists = [
        "Neurologist",
        "Radiologist",
        "Neurosurgeon",
        "Neuro-Oncologist"
    ]

    for specialist in specialists:

        content.append(
            Paragraph(
                f"• {specialist}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 20))

    # HOSPITALS

    content.append(
        Paragraph(
            "Recommended Neurology Centers",
            styles["Heading2"]
        )
    )

    hospitals = [

        "Apollo Hospitals",
        "Yashoda Hospitals",
        "KIMS Hospitals",
        "NIMS Hyderabad"

    ]

    for hospital in hospitals:

        content.append(
            Paragraph(
                f"• {hospital}",
                styles["Normal"]
            )
        )

    content.append(Spacer(1, 30))

    # DISCLAIMER

    content.append(
        Paragraph(
            "Disclaimer",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            "This report was generated using NeuroLis AI. "
            "The results are intended for educational and research "
            "purposes only and should not be considered a substitute "
            "for professional medical diagnosis or treatment.",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # FOOTER

    content.append(
        Paragraph(
            "Generated by NeuroLis AI Neurological Health Platform",
            styles["Italic"]
        )
    )

    doc.build(content)